### ISSUE TITLE
Invalid string input error on valid token

### ISSUE THREAD

**Issue by timheuer** [timheuer/JwtTools#4]
**Describe the bug**
Getting an invalid input string on a valid jwt token:

**To Reproduce**
Use this token:
`
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTQ3YWEtODUzYi1kMDgxMDFlZDE3Y2QiLCJuYW1lIjoiQWRtaW4iLCJqdGkiOiI0YmIyMjY4ZC02ZWE5LTRkYTUtODNjMS0yMzU1NmEzN2UxODAiLCJpYXQiOiIzLjExLjIwMjIgMjM6MjA6MDAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTY2NzYwNDAwMCwiaXNzIjoiSldUQXV0aGVudGljYXRpb25TZXJ2ZXIiLCJhdWQiOiJKV1RTZXJ2aWNlUG9zdG1hbkNsaWVudCJ9.KJUZ3EgEfV72l7hR1b25hL59vGtdzw5eKCTEvy1qYjg
`

**Expected behavior**
It decodes...jwt.io and DevToys works.

**Comment by timheuer** [comment]
Formatting issue on iat format: `3.11.2022 23:20:00` which is an invalid epoch time value per JWT specification

**Comment by BlueGreenWorld** [comment]
![image](https://user-images.githubusercontent.com/3757617/200334184-191bfb00-abef-4017-8380-64a5eba9b561.png)

What Can I Do ? About DateTime...

**Comment by timheuer** [comment]
@BlueGreenWorld use `DateTimeOffset` and `ToUnixTimeSeconds` extension method: https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.tounixtimeseconds?view=net-6.0

Example using your snippet above:
```
expires: DateTimeOffset.UtcNow.AddSeconds(30).ToUnixTimeSeconds();
```

**Comment by BlueGreenWorld** [comment]
i already tried, but datetime and long are incompatible.

**Comment by timheuer** [comment]
@BlueGreenWorld what library is that?  I can see...but bottom line it's not generating the correct output :-)

**Comment by BlueGreenWorld** [comment]
System.IdentityModel.Tokens.Jwt

**Comment by timheuer** [comment]
Hmm, fwiw, this worked for me:

```
using System.IdentityModel.Tokens.Jwt;

var token = new JwtSecurityToken("timheuer", "timsaudience", expires: DateTime.UtcNow.AddSeconds(30));

var jwt = new JwtSecurityTokenHandler().WriteToken(token);

Console.WriteLine(jwt);
Console.ReadLine();
```

It seems somewhere that you are writing the output is going wrong -- can you isolate a sample for me?

**Comment by BlueGreenWorld** [comment]
![image](https://user-images.githubusercontent.com/3757617/200666755-82c3acc5-8f03-40f4-995b-110613eb8293.png)

I included your example.

**Comment by BlueGreenWorld** [comment]
output : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTQ3YWEtODUzYi1kMDgxMDFlZDE3Y2QiLCJuYW1lIjoiQWRtaW4iLCJqdGkiOiJmOWJlMmY0OC04ODNlLTQ0MDQtYmQ3ZC1iOWUxZGNjNWYzZWYiLCJpYXQiOiI4LjExLjIwMjIgMjA6MTA6NTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW4iLCJVbGHFn8SxbV9Tb3J1bWx1c3UiXSwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy91c2VyZGF0YSI6WyIyIiwiMyJdLCJ1c2VyUm9sZTpBZG1pbiwgcm9sZUNsYWltOllldGtpQSI6IkEiLCJ1c2VyUm9sZTpBZG1pbiwgcm9sZUNsYWltOllldGtpQiI6IkIiLCJ1c2VyUm9sZTpBZG1pbiwgcm9sZUNsYWltOk1lbnUiOlsiMDAxIiwiMDAxMDAxIiwiMDAxMDAyIiwiMDAxMDAyMDAxIiwiMDAxMDAyMDAyIiwiMDAxMDAyMDAzIiwiMDAxMDAzIl0sInVzZXJSb2xlOlVsYcWfxLFtX1NvcnVtbHVzdSwgcm9sZUNsYWltOllldGtpQ0EiOiJDQSIsIk1lbnUiOiJbe1wiSWRcIjo0MCxcIktvZFwiOlwiMDAzMDA4XCIsXCJJY29uXCI6XCJcIixcIlVybFwiOlwiXCJ9LHtcIklkXCI6MjUsXCJLb2RcIjpcIjAwMlwiLFwiSWNvblwiOlwiXCIsXCJVcmxcIjpcIlwifSx7XCJJZFwiOjI2LFwiS29kXCI6XCIwMDIwMDFcIixcIkljb25cIjpcIlwiLFwiVXJsXCI6XCJcIn0se1wiSWRcIjoyNyxcIktvZFwiOlwiMDAyMDAyXCIsXCJJY29uXCI6XCJcIixcIlVybFwiOlwiXCJ9LHtcIklkXCI6MjgsXCJLb2RcIjpcIjAwMjAwM1wiLFwiSWNvblwiOlwiXCIsXCJVcmxcIjpcIlwifSx7XCJJZFwiOjI5LFwiS29kXCI6XCIwMDIwMDRcIixcIkljb25cIjpcIlwiLFwiVXJsXCI6XCJcIn0se1wiSWRcIjozMSxcIktvZFwiOlwiMDAyMDA2XCIsXCJJY29uXCI6XCJcIixcIlVybFwiOlwiXCJ9LHtcIklkXCI6MzIsXCJLb2RcIjpcIjAwM1wiLFwiSWNvblwiOlwiXCIsXCJVcmxcIjpcIlwifSx7XCJJZFwiOjMzLFwiS29kXCI6XCIwMDMwMDFcIixcIkljb25cIjpcIlwiLFwiVXJsXCI6XCJcIn0se1wiSWRcIjozNCxcIktvZFwiOlwiMDAzMDAyXCIsXCJJY29uXCI6XCJcIixcIlVybFwiOlwiXCJ9LHtcIklkXCI6MzUsXCJLb2RcIjpcIjAwMzAwM1wiLFwiSWNvblwiOlwiXCIsXCJVcmxcIjpcIlwifSx7XCJJZFwiOjM2LFwiS29kXCI6XCIwMDMwMDRcIixcIkljb25cIjpcIlwiLFwiVXJsXCI6XCJcIn0se1wiSWRcIjozNyxcIktvZFwiOlwiMDAzMDA1XCIsXCJJY29uXCI6XCJcIixcIlVybFwiOlwiXCJ9LHtcIklkXCI6MzgsXCJLb2RcIjpcIjAwMzAwNlwiLFwiSWNvblwiOlwiXCIsXCJVcmxcIjpcIlwifSx7XCJJZFwiOjM5LFwiS29kXCI6XCIwMDMwMDdcIixcIkljb25cIjpcIlwiLFwiVXJsXCI6XCJcIn0se1wiSWRcIjo0MCxcIktvZFwiOlwiMDAzMDA4XCIsXCJJY29uXCI6XCJcIixcIlVybFwiOlwiXCJ9LHtcIklkXCI6NDEsXCJLb2RcIjpcIjAwNFwiLFwiSWNvblwiOlwiXCIsXCJVcmxcIjpcIlwifV0iLCJleHAiOjE2Njc5MzgyODQsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZVBvc3RtYW5DbGllbnQifQ.qR1busEwJ2SXO647Q1lbFiOTM_79ZnlBUHZ0tHQUJRY

**Comment by BlueGreenWorld** [comment]
this sample in LiqPad and its ok
![image](https://user-images.githubusercontent.com/3757617/200667757-16645a79-4e99-4a49-a905-97439132595f.png)

**Comment by timheuer** [comment]
The `iat` portion is the issue -- where is the lines of code generating the issued at element?

![image](https://user-images.githubusercontent.com/4821/200669375-ac95ab4f-21e2-4e28-8cb3-0685f7ef5948.png)

**Comment by BlueGreenWorld** [comment]
sory sory sory
my fault =>  I forgot to write xtoken : var xjwt = new JwtSecurityTokenHandler().WriteToken(token);
fixt it and your code output is ok
eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJleHAiOjE2Njc5Mzk5MDcsImlzcyI6InRpbWhldWVyIiwiYXVkIjoidGltc2F1ZGllbmNlIn0.

**Comment by BlueGreenWorld** [comment]
I found somethings : its ok when remove my claims..
whats this ?!?!?!?

Like This  : 
var xtoken = new JwtSecurityToken(
                    _configuration["Jwt:Issuer"],
                    _configuration["Jwt:Audience"],
             ////claims,
                    expires: DateTime.UtcNow.AddSeconds(30),
                    signingCredentials: signIn
                );

**Comment by timheuer** [comment]
Yeah maybe one of those claims is bad.  But the net-net is something is generating an incorrect format for `iat` -- it isn't JwtSecurityToken as that is doing it right.

**Comment by BlueGreenWorld** [comment]
@timheuer I'm really sorry and thank you for your help. Because actually there is no problem. just misunderstanding...

![image](https://user-images.githubusercontent.com/3757617/200681464-be96b721-f7cd-4f29-98d6-76cbe9a6e77b.png)

**Comment by timheuer** [comment]
Great! glad to hear you found it!
